language: php
php:
  - 5.5
  - 5.4
install:
  - sudo apt-get install parallel
  - composer install --dev --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v